"""change CollaboratorInviteDB v1

Revision ID: 855de215b3e1
Revises: 4afb7635eca7
Create Date: 2025-03-25 04:01:51.876896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '855de215b3e1'
down_revision: Union[str, None] = '4afb7635eca7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

def upgrade() -> None:
    pass

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collaborator_invites',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('invitee_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('inviter_email', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('project_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('accepted', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='collaborator_invites_pkey')
    )
    # ### end Alembic commands ###
